/datum/customizer/organ/ears/generic
	customizer_choices = list(/datum/customizer_choice/organ/ears/generic)
	allows_disabling = TRUE
	default_disabled = TRUE

/datum/customizer_choice/organ/ears/generic
	name = "Ears"
	organ_type = /obj/item/organ/ears
	generic_random_pick = TRUE
	sprite_accessories = list(
		/datum/sprite_accessory/ears/cat,
		/datum/sprite_accessory/ears/axolotl,
		/datum/sprite_accessory/ears/bat,
		/datum/sprite_accessory/ears/bear,
		/datum/sprite_accessory/ears/bigwolf,
		/datum/sprite_accessory/ears/bigwolf_inner,
		/datum/sprite_accessory/ears/rabbit,
		/datum/sprite_accessory/ears/bunny,
		/datum/sprite_accessory/ears/big/rabbit_large,
		/datum/sprite_accessory/ears/big/rabbit_medium,
		/datum/sprite_accessory/ears/big/rabbit_small,
		/datum/sprite_accessory/ears/big/rabbit_floppy,
		/datum/sprite_accessory/ears/big/rabbit_floppyalt,
		/datum/sprite_accessory/ears/big/bunny_floppy,
		/datum/sprite_accessory/ears/bunny_perky,
		/datum/sprite_accessory/ears/bunny_long,
		/datum/sprite_accessory/ears/cat_big,
		/datum/sprite_accessory/ears/cat_normal,
		/datum/sprite_accessory/ears/cow,
		/datum/sprite_accessory/ears/curled,
		/datum/sprite_accessory/ears/deer,
		/datum/sprite_accessory/ears/eevee,
		/datum/sprite_accessory/ears/elf,
		/datum/sprite_accessory/ears/elfw,
		/datum/sprite_accessory/ears/elephant,
		/datum/sprite_accessory/ears/fennec,
		/datum/sprite_accessory/ears/fish,
		/datum/sprite_accessory/ears/fox,
		/datum/sprite_accessory/ears/vulp,
		/datum/sprite_accessory/ears/husky,
		/datum/sprite_accessory/ears/jellyfish,
		/datum/sprite_accessory/ears/kangaroo,
		/datum/sprite_accessory/ears/lab,
		/datum/sprite_accessory/ears/murid,
		/datum/sprite_accessory/ears/otie,
		/datum/sprite_accessory/ears/pede,
		/datum/sprite_accessory/ears/sergal,
		/datum/sprite_accessory/ears/shark,
		/datum/sprite_accessory/ears/skunk,
		/datum/sprite_accessory/ears/squirrel,
		/datum/sprite_accessory/ears/wolf,
		/datum/sprite_accessory/ears/perky,
		/datum/sprite_accessory/ears/antenna_simple1,
		/datum/sprite_accessory/ears/antenna_simple2,
		/datum/sprite_accessory/ears/antenna_simple3,
		/datum/sprite_accessory/ears/antenna_fuzzball1,
		/datum/sprite_accessory/ears/antenna_fuzzball2,
		/datum/sprite_accessory/ears/cobrahood,
		/datum/sprite_accessory/ears/cobrahoodears,
		/datum/sprite_accessory/ears/miqote,
		/datum/sprite_accessory/ears/lunasune,
		/datum/sprite_accessory/ears/sabresune,
		/datum/sprite_accessory/ears/possum,
		/datum/sprite_accessory/ears/raccoon,
		/datum/sprite_accessory/ears/mouse,
		/datum/sprite_accessory/ears/big/acrador_long,
		/datum/sprite_accessory/ears/big/acrador_short,
		/datum/sprite_accessory/ears/big/sandfox_large,
		/datum/sprite_accessory/ears/lynx,
		/datum/sprite_accessory/ears/zorzor,
		/datum/sprite_accessory/ears/naja_hood,
		/datum/sprite_accessory/ears/wispy,
		/datum/sprite_accessory/ears/small,
		/datum/sprite_accessory/ears/big/caustic/bunny_large,
		/datum/sprite_accessory/ears/ochre/fourfrill,
		/datum/sprite_accessory/ears/big/ochre/bunny_tall,
		/datum/sprite_accessory/ears/big/ochre/shadekin_round,
		/datum/sprite_accessory/ears/big/ochre/feather_horns,
		/datum/sprite_accessory/ears/big/ochre/party_plume,
		)
