
/datum/customizer/organ/tail/generic
	customizer_choices = list(/datum/customizer_choice/organ/tail/generic)
	allows_disabling = TRUE
	default_disabled = TRUE

/datum/customizer_choice/organ/tail/generic
	name = "Wild-Kin Tail"
	organ_type = /obj/item/organ/tail
	sprite_accessories = list(
		/datum/sprite_accessory/tail/cat,
		/datum/sprite_accessory/tail/monkey,
		/datum/sprite_accessory/tail/axolotl,
		/datum/sprite_accessory/tail/batl,
		/datum/sprite_accessory/tail/bats,
		/datum/sprite_accessory/tail/bee,
		/datum/sprite_accessory/tail/catbig,
		/datum/sprite_accessory/tail/twocat,
		/datum/sprite_accessory/tail/corvid,
		/datum/sprite_accessory/tail/cow,
		/datum/sprite_accessory/tail/data_shark,
		/datum/sprite_accessory/tail/eevee,
		/datum/sprite_accessory/tail/fennec,
		/datum/sprite_accessory/tail/fish,
		/datum/sprite_accessory/tail/fox,
		/datum/sprite_accessory/tail/fox2,
		/datum/sprite_accessory/tail/hawk,
		/datum/sprite_accessory/tail/horse,
		/datum/sprite_accessory/tail/husky,
		/datum/sprite_accessory/tail/insect,
		/datum/sprite_accessory/tail/kangaroo,
		/datum/sprite_accessory/tail/kitsune,
		/datum/sprite_accessory/tail/lab,
		//Caustic edit
		/datum/sprite_accessory/tail/large_snake,
		/datum/sprite_accessory/tail/large_snake_plain,
		/datum/sprite_accessory/tail/large_tails/large_shark,
		/datum/sprite_accessory/tail/lizard/kobold,
		/datum/sprite_accessory/tail/large_tails/alraune,
		//Caustic edit end
		//OV edit
		/datum/sprite_accessory/tail/large_tails/small_shadekin,
		/datum/sprite_accessory/tail/large_tails/large_shadekin,
		/datum/sprite_accessory/tail/kitsune_two,
		/datum/sprite_accessory/tail/kitsune_three,
		/datum/sprite_accessory/tail/kitsune_seven,
		/datum/sprite_accessory/tail/kitsune_nine,
		/datum/sprite_accessory/tail/large_tails/ochre/chonksqrl,
		//OV edit end
		/datum/sprite_accessory/tail/murid,
		/datum/sprite_accessory/tail/orca,
		/datum/sprite_accessory/tail/otie,
		/datum/sprite_accessory/tail/rabbit,
		/datum/sprite_accessory/tail/redpanda,
		/datum/sprite_accessory/tail/pede,
		/datum/sprite_accessory/tail/sergal,
		/datum/sprite_accessory/tail/shark,
		/datum/sprite_accessory/tail/shepherd,
		/datum/sprite_accessory/tail/australian_shepherd,
		/datum/sprite_accessory/tail/jackal,
		/datum/sprite_accessory/tail/skunk,
		/datum/sprite_accessory/tail/stripe,
		/datum/sprite_accessory/tail/straighttail,
		/datum/sprite_accessory/tail/squirrel,
		/datum/sprite_accessory/tail/tamamo_kitsune,
		/datum/sprite_accessory/tail/tentacle,
		/datum/sprite_accessory/tail/tiger,
		/datum/sprite_accessory/tail/wolf,
		/datum/sprite_accessory/tail/guilmon,
		/datum/sprite_accessory/tail/sharknofin,
		/datum/sprite_accessory/tail/raptor,
		/datum/sprite_accessory/tail/lunasune,
		/datum/sprite_accessory/tail/spade,
		/datum/sprite_accessory/tail/leopard,
		/datum/sprite_accessory/tail/deer,
		/datum/sprite_accessory/tail/raccoon,
		/datum/sprite_accessory/tail/sabresune,
		/datum/sprite_accessory/tail/lizard/smooth,
		/datum/sprite_accessory/tail/lizard/dtiger,
		/datum/sprite_accessory/tail/lizard/ltiger,
		/datum/sprite_accessory/tail/lizard/spikes,
		/datum/sprite_accessory/tail/rattlesnake,
		/datum/sprite_accessory/tail/lynx,
		/datum/sprite_accessory/tail/owl,
		/datum/sprite_accessory/tail/forked_long,
		/datum/sprite_accessory/tail/haven,
		/datum/sprite_accessory/tail/swallow,
		/datum/sprite_accessory/tail/zorzor,
		/datum/sprite_accessory/tail/large_snake,
		/datum/sprite_accessory/tail/large_snake_plain
		)
