#define FOOD_CAT_COMBINATION "Combination"
#define FOOD_CAT_CAKES "Cakes"
#define FOOD_CAT_BAKED "Baked Goods"
#define FOOD_CAT_RICE "Rice Meals"
#define FOOD_CAT_SANDWICH "Sandwiches"
#define FOOD_CAT_EGGS "Eggs"
#define FOOD_CAT_SEAFOOD "Seafood"
#define FOOD_CAT_DRYING "Drying Rack"
#define FOOD_CAT_STEW "Stews"
