/datum/species/dullahan //these need a special definition due to a custom Soul feature
	customizers = list(
		/datum/customizer/organ/eyes/generic,
		/datum/customizer/bodypart_feature/hair/head/generic, 
		/datum/customizer/bodypart_feature/hair/facial/humanoid, 
		/datum/customizer/bodypart_feature/accessory,
		/datum/customizer/bodypart_feature/face_detail,
		/datum/customizer/bodypart_feature/underwear,
		/datum/customizer/bodypart_feature/legwear,
		/datum/customizer/bodypart_feature/piercing,
		/datum/customizer/organ/penis/anthro,
		/datum/customizer/organ/breasts/human,
		/datum/customizer/organ/vagina/human_anthro,
		/datum/customizer/organ/belly/human,
		/datum/customizer/organ/butt/human, 
		/datum/customizer/organ/testicles/anthro,
		/datum/customizer/organ/tail/generic,
		/datum/customizer/organ/tail_feature/anthro,
		/datum/customizer/organ/snout/generic,
		/datum/customizer/organ/ears/generic,
		/datum/customizer/organ/horns/generic,
		/datum/customizer/organ/frills/generic,
		/datum/customizer/organ/wings/generic,
		/datum/customizer/organ/neck_feature/generic,
		/datum/customizer/organ/soul/fire,
		)
